#before_install:
#  # Install makeindex, if you do not use an index you can remove this (also remove the extra makeindex call).
#  - sudo apt-get install texlive-binaries

install:
        - cd ./testing
        - source ./install.sh
cache:
  directories:
    - /tmp/texlive
script:
 - cd $TRAVIS_BUILD_DIR/book/
 - latexmk -lualatex -latexoption="-interaction nonstopmode -halt-on-error -file-line-error -shell-escape"   linearalgebra-book.tex
 - latexmk -lualatex -latexoption="-interaction nonstopmode -halt-on-error -file-line-error -shell-escape"   linearalgebra-instructor.tex
   #deploy:
   #  provider: releases
   #  api_key:
   #    secure: GK0T9i6YKZlKmxurW4B8lkBGC
   #  file:
   #  - ./problemsets-mat223/linearalgebra.pdf
   #  skip_cleanup: true
   #  on:
   #    tags: true
   #    branch: master
